export const metadata = {
  title:       "Terms of Use",
  description: "Terms of use for CUBOSAPIENS. Free browser tools with no accounts required. Read our terms before using our platform.",
  openGraph: {
    title:       "Terms of Use",
    description: "Read the terms of use for CUBOSAPIENS — free tools, games and AI for everyone.",
    url:         "https://cubosapiens.world/terms",
  },
}

export default function TermsPage()
{
  return (
    <div className="page-container">
      <div className="page-hero">
        <span className="section-tag">Legal</span>
        <h1 className="page-hero-title">Terms of Use</h1>
        <p className="page-hero-sub">Last updated: 15 March 2026. By using CUBOSAPIENS you agree to these terms.</p>
      </div>

      <div className="legal-content">

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using cubosapiens.world or any of its tool subdomains, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use our platform. These terms apply to all visitors and users of CUBOSAPIENS.</p>

        <h2>2. About CUBOSAPIENS</h2>
        <p>CUBOSAPIENS is a free, browser-based platform providing tools, games and AI utilities for general internet users, students, and developers. Our core philosophy is that every useful tool on the internet should be accessible to everyone without requiring accounts, subscriptions, or payments.</p>
        <p>All tool processing occurs within your browser. We do not upload, store, or process your personal files on any server. Your photos, documents, and data remain on your device at all times.</p>

        <h2>3. No Account Required</h2>
        <p>CUBOSAPIENS does not require you to create an account to use our core tools. Some future features such as saved tool history or personalised settings may optionally require an account. Any account features will be clearly marked and entirely opt-in. Account functionality, where available, will be managed independently by each tool or game and governed by that tool&apos;s specific terms.</p>

        <h2>4. Permitted Use</h2>
        <p>You may use CUBOSAPIENS for any lawful personal, educational, or professional purpose. We encourage students, developers, and creators to use our tools freely in their work and projects.</p>

        <h2>5. Prohibited Use</h2>
        <p>You must not use CUBOSAPIENS or its tools to:</p>
        <ul>
          <li>Create fraudulent, misleading, or deceptive content intended to deceive others</li>
          <li>Falsify GPS location data with intent to commit fraud or deception</li>
          <li>Violate any applicable local, national, or international law or regulation</li>
          <li>Infringe on the intellectual property rights of others</li>
          <li>Attempt to reverse engineer, scrape, or automate access to our platform in ways that disrupt service for other users</li>
          <li>Use our platform to distribute malware, spam, or harmful content</li>
        </ul>

        <h2>6. Intellectual Property</h2>
        <p>The CUBOSAPIENS platform, including its design, code, and content, is open-source software licensed under the MIT License. You are free to use, modify, and distribute the code in accordance with that licence. The CUBOSAPIENS name and logo are trademarks of the project and may not be used without permission.</p>
        <p>You retain full ownership of any content you create using our tools. We make no claim to your photos, documents, or any output generated by our platform.</p>

        <h2>7. Third-Party Services</h2>
        <p>CUBOSAPIENS integrates third-party services including Cloudflare, Supabase, OpenStreetMap, Esri World Imagery, and Google AdSense. Your use of these services through our platform is subject to their respective terms of service. We are not responsible for the availability, accuracy, or content of third-party services.</p>

        <h2>8. Advertising</h2>
        <p>CUBOSAPIENS displays advertisements through Google AdSense to fund the platform and keep it free. Advertisements are served by Google and are clearly distinguished from our content. We do not endorse any advertised products or services.</p>

        <h2>9. Disclaimer of Warranties</h2>
        <p>CUBOSAPIENS is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties of any kind, either express or implied. We do not warrant that the platform will be uninterrupted, error-free, or free of viruses. GPS coordinates provided by our tools are sourced from third-party services and we make no representation as to their accuracy. Use location-based features at your own discretion.</p>

        <h2>10. Limitation of Liability</h2>
        <p>To the fullest extent permitted by applicable law, CUBOSAPIENS and its developers shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the platform. Our total liability for any claim arising from these terms shall not exceed zero rupees, as the platform is provided entirely free of charge.</p>

        <h2>11. Open Source</h2>
        <p>CUBOSAPIENS is an open-source project. The source code is available on GitHub. Contributions are welcome under our contribution guidelines. By contributing code, you agree that your contributions will be licensed under the same MIT License as the rest of the project.</p>

        <h2>12. Changes to Terms</h2>
        <p>We reserve the right to modify these terms at any time. Changes will be reflected by updating the date at the top of this page. Continued use of CUBOSAPIENS after changes constitutes your acceptance of the updated terms.</p>

        <h2>13. Governing Law</h2>
        <p>These terms are governed by and construed in accordance with the laws of India. Any disputes arising from these terms shall be subject to the jurisdiction of the courts of Chennai, Tamil Nadu, India.</p>

        <h2>14. Contact</h2>
        <p>For questions about these terms, contact us at <a href="mailto:cubosapiens@gmail.com" className="about-link">cubosapiens@gmail.com</a> or visit our <a href="/contact" className="about-link">contact page</a>.</p>

      </div>
    </div>
  )
}