name = "cubosapiens-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = "apps/web/.open-next/worker.js"

[assets]
directory = "apps/web/.open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_API_URL = "https://api.cubosapiens.world"