export const IconMap: Record<string, any> = {
  "cgpa-calculator.png": require('./cgpa-calculator.png'),
  "color-palette.png": require('./color-palette.png'),
  "cubo-snake.png": require('./cubo-snake.png'),
  "cyber-runner.png": require('./cyber-runner.png'),
  "da-vinci-fly.png": require('./da-vinci-fly.png'),
  "dsa-sheet.png": require('./dsa-sheet.png'),
  "gps-cam.png": require('./gps-cam.png'),
  "gst-calculator.png": require('./gst-calculator.png'),
  "hp-quiz.png": require('./hp-quiz.png'),
  "icon-192.png": require('./icon-192.png'),
  "icon-512.png": require('./icon-512.png'),
  "image-editor.png": require('./image-editor.png'),
  "img-convert.png": require('./img-convert.png'),
  "json-formatter.png": require('./json-formatter.png'),
  "markdown-editor.png": require('./markdown-editor.png'),
  "password-gen.png": require('./password-gen.png'),

  "Picon-128.png": require('./Picon-128.png'),
  "Picon-512.png": require('./Picon-512.png'),
  "Plogo.png": require('./Plogo.png'),
  "pomodoro-timer.png": require('./pomodoro-timer.png'),
  "qr-generator.png": require('./qr-generator.png'),
  "stick-man-iron-domination.png": require('./stick-man-iron-domination.png'),
  "stickman-idle-rpg.png": require('./stickman-idle-rpg.png'),
  "sudoku.png": require('./sudoku.png'),
  "text-analyse.png": require('./text-analyse.png'),
  "trading-empire.png": require('./trading-empire.png'),
  "vid-framer.png": require('./vid-framer.png'),
  "xo.png": require('./xo.png'),
};

